version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: guestara-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guestara
      POSTGRES_USER: guestara
      POSTGRES_PASSWORD: guestara
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
      - ./src/db/seed.sql:/docker-entrypoint-initdb.d/002_seed.sql
  
  api:
    build: .
    container_name: guestara-api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: guestara
      DB_PASSWORD: guestara
      DB_NAME: guestara
      PORT: 3000
    ports:
      - "3000:3000"
      
volumes:
  postgres_data:
